### ISSUE TITLE
Projects Section Links

### ISSUE THREAD

**Issue by Zemerik** [Abhishek9503/My-ProtFolio#3]
Currently, the hover effect on the projects is working perfectly fine, but users are unable to view your projects by clicking on them. To fix this issue, you may want to redirect users to your project link when they click on a certain project so that users can see your projects. 

Regards, 
Zemerik

**Comment by Abhishek9503** [comment]
Yes, you are right , in  recent update of my portfolio i forgot to add the live demo and navigation button will surely add in the next release soon, Thank you for pointing it out

**Comment by Zemerik** [comment]
No problem Abhishek. You have a Great Portfolio, glad I could help👍.
